spring.profiles.active: test
server:
  port: 8080
---
spring:
  profiles: test
  jpa:
    show_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/payments
    driverClassName: org.postgresql.Driver
    username: tech
    password: test